//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneDesignSystems.arCADia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoneDesignSystems.arCADia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon arCADia {
            get {
                object obj = ResourceManager.GetObject("arCADia", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates contiguities using the  DE-9IM topological model that is implemented through the Net Topology Suite library. The resulted file has the following structure: &lt;AreaId&gt;, &lt;NeigId&gt;..
        /// </summary>
        internal static string ListInfo_1 {
            get {
                return ResourceManager.GetString("ListInfo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented yet..
        /// </summary>
        internal static string ListInfo_2 {
            get {
                return ResourceManager.GetString("ListInfo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented yet..
        /// </summary>
        internal static string ListInfo_3 {
            get {
                return ResourceManager.GetString("ListInfo_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates centroids constrained by the boundaries of each polygon using the Net Topology Suite library. The resulted file has the following structure: &lt;AreaId&gt;, &lt;CoordX&gt;, &lt;CoordY&gt;..
        /// </summary>
        internal static string ListInfo_4 {
            get {
                return ResourceManager.GetString("ListInfo_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates centroids constrained by the boundaries of each polygon using the Net Topology Suite library. The resulted file has the following structure: &lt;AreaId&gt;, &lt;Lat&gt;, &lt;Lon&gt;..
        /// </summary>
        internal static string ListInfo_4a {
            get {
                return ResourceManager.GetString("ListInfo_4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates centroids constrained by the boundaries of each polygon using the Net Topology Suite library. Also, gets the Area and Perimeter. The resulted file has the following structure: &lt;AreaId&gt;, &lt;CoordX&gt;, &lt;CoordY&gt;, &lt;Area&gt;, &lt;Perimeter&gt;..
        /// </summary>
        internal static string ListInfo_5 {
            get {
                return ResourceManager.GetString("ListInfo_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates centroids constrained by the boundaries of each polygon using the Net Topology Suite library. Also, calculates the Area and the Perimeter using geodetic functions. The resulted file has the following structure: &lt;AreaId&gt;, &lt;Lat&gt;, &lt;Lon&gt;, &lt;Area&gt;, &lt;Perimeter&gt;..
        /// </summary>
        internal static string ListInfo_5a {
            get {
                return ResourceManager.GetString("ListInfo_5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented yet..
        /// </summary>
        internal static string ListInfo_6 {
            get {
                return ResourceManager.GetString("ListInfo_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented yet..
        /// </summary>
        internal static string ListInfo_7 {
            get {
                return ResourceManager.GetString("ListInfo_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented yet..
        /// </summary>
        internal static string ListInfo_8 {
            get {
                return ResourceManager.GetString("ListInfo_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented yet..
        /// </summary>
        internal static string ListInfo_9 {
            get {
                return ResourceManager.GetString("ListInfo_9", resourceCulture);
            }
        }
    }
}
